# See https://ezcv.readthedocs.io for documentation
address: ''
avatar: ''
background: ''
biography: ''
company: ''
email: ''
examples: true
ignore_exif_data: false
name: ''
phone: ''
resume: false
role: ''
theme: dimension
ua_code: ''
